
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cuser/login', array('action' => 'login')));
echo $this->form()->openTag($form);
?>

<div class="row">
	<div class="container col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
			<table>
				<tr>
					<?php $element = $form->get('username'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
					<td><?php echo $this->formelementerrors($element)?></td>
				</tr>
				<tr>
					<?php $element = $form->get('password'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
					<td><?php echo $this->formelementerrors($element)?></td>
				</tr>
				<tr>
					<td></td>
					<td><?php echo $this->formelement($form->get('login'))?></td>
				</tr>
			</table>
			</div>
		</div>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
