<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cuser/login', array('action' => 'register')));
echo $this->form()->openTag($form);
echo $this->formhidden($form->get('id'));
echo $this->formhidden($form->get('role'));
echo $this->formhidden($form->get('security'));

?>

<div class="row">
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-body">
			<table>
				<tr>
					<?php $element = $form->get('fullName'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
				</tr>
				<tr>
					<td></td><td><?php echo $this->formelementerrors($element)?></td>
				</tr>
				<tr>
					<?php $element = $form->get('username'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
				</tr>
				<tr>
					<td></td><td><?php echo $this->formelementerrors($element)?></td>
				</tr>

				<tr>
					<?php $element = $form->get('password'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
				<tr>
					<td></td><td><?php echo $this->formelementerrors($element)?></td>
				</tr>

				<tr>
					<?php $element = $form->get('passwordAgain'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
				</tr>
				<tr>
					<td></td><td><?php echo $this->formelementerrors($element)?></td>
				</tr>

				<tr>
					<?php $element = $form->get('email'); ?>
					<td><?php echo $this->formlabel($element)?></td>
					<td><?php echo $this->formelement($element)?></td>
				</tr>
				<tr>
					<td></td><td><?php echo $this->formelementerrors($element)?></td>
				</tr>					
				<tr>
					<td></td>
					<td><?php echo $this->formelement($form->get('submit'))?></td>
				</tr>
			</table>
			</div>
		</div>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
